version: '3.0'

expectations:
  population_size: 50000

actions:


################
#  Flow chart  #
################

  flow_chart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv

  generate_flowchart:
    run: stata-mp:latest analysis/000_cr_flow_chart.do
    needs: [flow_chart]
    outputs:
      moderately_sensitive:
        cohort: output/000_flow_chart.log
        
