version: '3.0'

expectations:
  population_size: 50000

actions:


################
#  Flow chart  #
################

  flow_chart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
    outputs:
      highly_sensitive:
        cohort: output/input_flow_chart.csv
